nube_inmobiliaria/core/urls.py
from django.conf.urls.defaults import patterns, url, include
from properties.views import user_properties_view
from core.views import HomeView, AboutView, FaqView
from core.views import (home_profile_view, members_view,
                        documents_profile_view,
                        edit_profile_view, favourites_view,
                        buy_ad_view, pay_ad_view, ad_buyed_view,
                        ad_not_buyed_view, membership_select_view,
                        membership_pay_view, member_detail_view)


URLS = (
    url(r'^$', HomeView.as_view(), name='home'),

    url(r'^acerca-de/$', AboutView.as_view(), name='about'),

    url(r'^FAQ/$', FaqView.as_view(), name='faq'),

    url(r'^perfil/$', home_profile_view, name='profile-home'),

    url(r'^perfil/mis-propiedades/$', user_properties_view,
        name='profile-properties'),

    url(r'^perfil/documentacion/$', documents_profile_view,
        name='profile-documents'),

    url(r'^perfil/editar/$', edit_profile_view, name='profile-edit'),

    url(r'^perfil/miembros/$', members_view, name='profile-members'),
    url(r'^perfil/miembros/(?P<pk>\d+)/$', member_detail_view,
        name='profile-member-detail'),
    url(r'^perfil/cuenta/$', user_properties_view, name='profile-account'),

    url(r'^perfil/favoritos/$', favourites_view, name='profile-favourites'),

    # select, buy ads
    url(r'^perfil/comprar/$', buy_ad_view, name='profile-buy'),
    url(r'^perfil/pagar/(?P<pk>\d+)/$', pay_ad_view, name='profile-pay'),

    # select, buy memberships
    url(r'^perfil/selecionar-membresia/$', membership_select_view,
        name='profile-select-membership'),
    url(r'^perfil/pagar-membresia/(?P<pk>\d+)/$', membership_pay_view,
        name='profile-pay-membership'),

    # result of payment
    url(r'^perfil/compra-realizada/$', ad_buyed_view, name='profile-ad-buyed'),
    url(r'^perfil/compra-cancelada/$', ad_not_buyed_view,
        name='profile-ad-canceled'),

    (r'^paypal/r-ds/dsfe/gpsd290-+sd/r/ef26/',
     include('paypal.standard.ipn.urls')),
)

urlpatterns = patterns('', *URLS)

nube_inmobiliaria/nube_inmobiliaria/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^pagina/', include('django.contrib.flatpages.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.urls')),
    url(r'^inmuebles/', include('properties.urls')),
    url(r'^contacto/', include('contact_form.urls')),
    url(r'^cuentas/logout/', 'django.contrib.auth.views.logout',
        {'next_page': '/'}, name='logout'),
    url(r'^cuentas/', include('django.contrib.auth.urls')),
    url(r'^cuentas/', include('registration.backends.email_terms.urls')),
    url(r'^api/', include('sepomex.api.urls')),
    url(r'^ads/', include('ads.api.urls')),
)


if settings.DEBUG:
    if 'rosetta' in settings.INSTALLED_APPS:
        urlpatterns += (url(r'^rosetta/', include('rosetta.urls')),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

nube_inmobiliaria/properties/urls.py
from django.conf.urls.defaults import patterns, url
from properties.views import (form_view, create_property_view,
                              property_detail_view, property_edit_view,
                              create_image_view, search_view,
                              set_favourite_view, delete_image_view,
                              set_main_picture_view, custom_search_form_view,
                              delete_property_view)


urlpatterns = patterns('',
    url(r'^crear/$', create_property_view, name='property-create'),
    url(r'^buscar/$', search_view, name='property-search'),
    url(r'^formulario/$', form_view, name='property-form'),
    url(r'^(?P<pk>\d+)/$', property_detail_view, name='property-detail'),
    url(r'^(?P<pk>\d+)/editar/$', property_edit_view, name='property-edit'),
    url(r'^(?P<pk>\d+)/imagen-nueva/$', create_image_view,
        name='property-add-image'),
    url(r'^(?P<pk>\d+)/borrar-imagen/(?P<image_id>\d+)$', delete_image_view,
        name='property-delete-image'),
    url(r'^(?P<pk>\d+)/poner-imagen/(?P<image_id>\d+)$', set_main_picture_view,
        name='property-set-main-picture'),
    url(r'^set-favorite/(?P<pk>\d+)/$', set_favourite_view,
        name='properties-set-favourite'),
    url(r'^borrar-inmueble/(?P<pk>\d+)/$', delete_property_view,
        name='properties-delete'),
    url(r'^custom-search-form/$', custom_search_form_view,
        name='properties-custom-form'),
)

nube_inmobiliaria/properties/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from django.contrib.humanize.templatetags.humanize import intcomma
from django.db.models import BooleanField, CharField, TextField
from django.db.models.query import QuerySet

from sepomex.models import State, Settlement
from currencies.models import Currency
from ads.models import Ad


ORIENTATION_CHOICES = (
    ('N', 'norte'),
    ('S', 'sur'),
    ('E', 'este'),
    ('O', 'oeste'),
)


class SubClassingQuerySet(QuerySet):
    def __getitem__(self, k):
        result = super(SubClassingQuerySet, self).__getitem__(k)
        if isinstance(result, models.Model):
            return result.as_leaf_class()
        else:
            return result

    def __iter__(self):
        for item in super(SubClassingQuerySet, self).__iter__():
            yield item.as_leaf_class()


class InmuebleManager(models.Manager):
    def get_query_set(self):
        return SubClassingQuerySet(self.model)


def choices_range(start, end, by=1):
    return [(i, i) for i in range(start, end + 1, by)]


class AdicionalesImportantesMixin(models.Model):

    EXCELENT = u'E'
    BUENO = u'B'
    REMODELAR = u'R'

    CONSERVACION = (
        (EXCELENT, 'excelent'),
        (BUENO, 'bueno'),
        (REMODELAR, 'remodelar'),
    )

    FORMA_ENTREGA = (
        ('G', 'obra gris'),
        ('B', 'obra blanca'),
        ('T', 'terminada'),
        ('A', 'amueblado'),
    )

    conservacion = CharField(u'conservación', max_length=2,
                             choices=CONSERVACION,
                             default=BUENO)
    estacionamientos = models.SmallIntegerField('No. Estacionamientos',
                                                default=0)

    forma_entrega = models.CharField(u'forma de entrega',
                                     max_length=1, choices=FORMA_ENTREGA)

    class Meta:
        abstract = True


class ExtrasInmuebleMixin(models.Model):

    tiene_alacena = BooleanField('alacena')
    tiene_closet_blancos = BooleanField('closet de blancos')
    tiene_closets = BooleanField('closets')
    tiene_area_lavado = BooleanField('Área de lavado')
    tiene_servicio = BooleanField('Cuarto de Servicio')
    tiene_sala_tele = BooleanField('Sala de tele')
    tiene_estudio = BooleanField('Estudio')
    tiene_biblioteca = BooleanField('biblioteca')

    class Meta:
        abstract = True


class ServiciosCondominioMixin(models.Model):

    tiene_snack_bar = BooleanField('snack bar')
    tiene_salon_fiesta = BooleanField('salón de fiestas')
    tiene_pista_jogging = BooleanField('pista jogging')
    tiene_ludoteca = BooleanField('ludoteca')

    class Meta:
        abstract = True


class TemperaturaMixin(models.Model):
    tiene_calefaccion = BooleanField('calefacción')
    tiene_acondicionado = BooleanField('aire acondicionado')

    class Meta:
        abstract = True


class Imagen(models.Model):
    EDIT_SIZE = "165x85"
    PROFILE_LIST_SIZE = "175x110"
    descripcion = CharField('descripción', max_length=140, blank=True)
    imagen = models.ImageField('imágen', upload_to='properties')


class Inmueble(models.Model):

    VENTA = u'V'
    RENTA = u'R'
    TRASPASO = u'T'

    TIPOS_DE_TRANSACCION = (
        (VENTA, u'Venta'),
        (RENTA, u'Renta'),
        (TRASPASO, u'Traspaso'),
    )

    VISIBLE = 'VIS'
    ESCONDIDA = 'ESC'
    BORRADA = 'BOR'

    ESTADOS = (
        (VISIBLE, 'visible'),
        (ESCONDIDA, 'escondida'),
        (BORRADA, 'borrada'),
    )

    COMISION_CHOICES = (
        (20, 20),
        (30, 30),
        (40, 40),
        (50, 50),
        (60, 60),
    )

    user = models.ManyToManyField(User, editable=False)
    favourite_of = models.ManyToManyField(User, editable=False,
                                          related_name='favourites')
    colonia = models.ForeignKey(Settlement)
    calle_y_num = TextField(u'calle y número', max_length=300,
                            blank=True)
    referencias = TextField(u'referencia ubicación', max_length=300,
                            blank=True)
    precio = models.DecimalField(u'Precio', max_digits=14,
                                 decimal_places=2)
    precio_global = models.DecimalField(max_digits=14,
                                        decimal_places=2, editable=False,
                                        null=True)
    divisa = models.ForeignKey(Currency)
    transaccion = CharField(u'Tipo de transacción',
                            max_length=1, choices=TIPOS_DE_TRANSACCION)
    descripcion = TextField(u'Descripción del inmueble', blank=True)
    observaciones = TextField(u'Observaciones', blank=True)
    pct_pactada = models.FloatField(u'% Comisión Pactada')
    pct_compartir = models.IntegerField(u'% Comisión a Compartir',
                                        choices=COMISION_CHOICES)

    lat = models.FloatField(editable=False, null=True)
    lon = models.FloatField(editable=False, null=True)

    main_picture = models.ForeignKey('Imagen', null=True, blank=True,
                                     editable=False,
                                     related_name='main_pictures')
    imagenes = models.ManyToManyField('Imagen', null=True, blank=True)
    state = models.CharField('estado', max_length=3, default=ESCONDIDA,
                             choices=ESTADOS, editable=False)
    add_date_time = models.DateTimeField('Fecha que se agrego',
                                         auto_now_add=True, editable=False)
    last_update = models.DateTimeField('actualización', auto_now=True,
                                       editable=False)
    type = models.CharField('tipo inmueble', max_length=3, editable=False)

    ad = models.ForeignKey(Ad, blank=True, null=True, verbose_name='anuncio')
    _surface = models.IntegerField(editable=False)

    full_objects = InmuebleManager()
    objects = models.Manager()

    # TODO: Reorganizar esto!!
    _exclude_fields = ('type', 'ad', 'add_date_time', 'user', 'referencias')
    _address_fields = ('estado', 'codigo_postal', 'colonia', 'calle_y_num')
    _general_fields_free = ('precio', 'mantenimiento', 'nombre_desarrollo',
                            'superficie_total', 'superficie_construida',
                            'habitaciones', 'vestidores', 'banos',
                            'medios_banos', 'edad', 'tiene_family_room',
                            'tiene_antecomedor', 'tiene_desnivel',
                            'oficinas_privadas', 'salas_de_juntas',
                            'num_elevadores', 'frente', 'fondo',)
    _general_fields_choices = ('divisa', 'transaccion', 'niveles',
                               'piso', 'niveles_permitidos',
                               'pct_sin_construir', 'areas_comunes',
                               'tiene_mezanine', 'altura', 'tipo_fachada',
                               'tiene_hidraulica_electrica', 'tiene_tapanco',
                               'resistencia_piso', 'anden', 'tiene_oficinas',
                               'tiene_rampa', 'entrada_luz', 'tiene_patio',
                               'tiene_banos', 'tiene_banos_ejecutivos',
                               'tiene_doble_altura', 'tiene_roof_garden',)

    _extras_left = (
        'orientacion', 'tiene_alacena', 'tiene_closet_blancos',
        'tiene_closets', 'tiene_area_lavado', 'tiene_servicio',
        'tiene_sala_tele', 'tiene_estudio', 'tiene_biblioteca',
        'tiene_calefaccion', 'tiene_acondicionado',
        'tiene_panoramica',
    )

    _extras_right = (
        'tiene_bodega', 'tiene_gimnasio', 'tiene_jardin',
        'tiene_alberca', 'tiene_tenis', 'tiene_padel',
        'tiene_planta_luz', 'tiene_terraza', 'tiene_seguridad',
        'tiene_cocina', 'tiene_comedor', 'tiene_recepcion',
        'tiene_sisterna', 'tiene_seguridad',
    )

    _condominio_left = ('tiene_snack_bar', 'tiene_salon_fiesta')
    _condominio_right = ('tiene_pista_jogging', 'tiene_ludoteca')

    _adicionales_left = ('conservacion', 'estacionamientos',
                         'tipo_ubicacion')
    _adicionales_right = ('forma_entrega', 'estacionamientos_visitas')

    _general_fields = _general_fields_free + _general_fields_choices
    _extras_inmueble = _extras_left + _extras_right
    _condominio = _condominio_left + _condominio_right
    _adicionales = _adicionales_left + _adicionales_right

    _all_fields = _general_fields + _extras_inmueble\
        + _condominio + _adicionales

    def get_google_maps_query(self):
        colonia = self.colonia
        municipality = colonia.municipality
        return u"{municipality}, {CP}, {state}, "\
            u"México".format(CP=self.codigo_postal,
                              municipality=municipality.name,
                              state=municipality.state.name)

    def delete(self, *args, **kwargs):
        #self.imagenes.all().delete()
        if self.ad:
            self.ad.set_ready()
        super(Inmueble, self).delete(*args, **kwargs)

    @property
    def estado(self):
        return State.objects.distinct()\
            .get(municipality=self.municipio)

    @property
    def codigo_postal(self):
        return str(self.colonia.postal_code.number).rjust(5, '0')

    @property
    def owner(self):
        try:
            return self.__owner
        except AttributeError:
            pass
        self.__owner = self.user.all()[0]
        return self.__owner

    @property
    def municipio(self):
        return self.colonia.municipality

    def update_global_price(self, save=True):
        """
        Update global price to USD
        This method is not recomended
        to update the whole database
        """
        self.precio_global = self.divisa.convert_to_global(self.precio)
        if save:
            self.save()

    def save(self, *args, **kwargs):
        if not self.type:
            self.type = self._type

        self._set_surface()
        self.update_global_price(save=False)

nube_inmobiliaria/templates/properties/create.html
{% extends "core/profile/base.html" %}

{% block extra_head %}
{{ form.media }}
<script type="text/javascript">
var get_form_url = '{% url property-form %}';

</script>

{% endblock %}

{% block profile_id %}anadir{% endblock %}


{% block profile_class %}padding{% endblock %}


{% block profile_title %}A&ntilde;adir Propiedad{% endblock %}


{% block profile_content %}
<ul>
	{% for field in property_form.visible_fields %}
		{% if field.errors %}
			<li class="error">
			{{ field.label }}: {{ field.errors|join:" ," }}
			</li>
		{% endif %}
	{% endfor%}
</ul>


<div class="right">
{{ form }}
</div>
<div class="clear"></div>
<hr>
<form action="" method="post" id="main_form" autocomplete="off">
	{% csrf_token %}
	<input type="hidden" name="property-type" id="property-type" value="{{ property_type }}"/>
	<div id="form_content" class="padding">
		{{ property_form.as_formated_div }}
	</div>
	<input type="submit" value="Guardar y Agregar Fotos" id="create-button" class="continuar"/>
</form>
{% endblock %}

nube_inmobiliaria/templates/properties/detail.html
{% extends "base_login.html" %}

{% load profile thumbnail humanize property %}


{% block extra_head %}
<link rel="stylesheet" href="{{ STATIC_URL }}css/flexslider.css" type="text/css" media="screen">
<script defer src="{{ STATIC_URL }}js/jquery.flexslider-min.js"></script>
<script type="text/javascript">
    $(window).load(function(){
      $('#carousel').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        itemWidth: 140,
        itemMargin: 10,
        asNavFor: '#slider'
      });
      
      $('#slider').flexslider({
        animation: "slide",
        controlNav: false,
        animationLoop: false,
        slideshow: false,
        sync: "#carousel",
        start: function(slider){
          $('body').removeClass('loading');
        }
      });

    $('#btn_mapa').click(function(e){
		e.preventDefault();
		$('#map-image').click();
		    });

    /* TODO: Promote to some library */
    $('#btn_favoritos').click(function(e){
		    e.preventDefault();
		    $.post("{% url properties-set-favourite object.id %}", function(){
			    $('#btn_favoritos').toggleClass('favourite');
			    });
		});
    });

   
</script>
{% endblock %}


{% block subwrapper_id %}propiedad{% endblock %}

{% block profile_left %}
<div class="redbox">

	{% if owner == user %}
	<a href="{% url property-edit object.id %}"
		style="position:absolute;
		right:10px;
		top:4px;"> Editar </a>
	{% endif %}
	<h1>{{ object.tipo_inmueble|upper }}</h1>
    <h2>Referencia: {{ object.id }}</h2>
	<table>
		<tr>
			<th>Estado:</th>
			<td>{{ object.estado }}</td>
		</tr>
		<tr>
			<th>Municipio:</th>
			<td>{{ object.municipio }}</td>
		</tr>
		<tr>
			<th>Código Postal:</th>
			<td>{{ object.codigo_postal }}</td>
		</tr>
		<tr>
			<th>Colónia:</th>
			<td>{{ object.colonia }}</td>
		</tr>

		{% if object.referencias %}
		<tr>
			<th>Referencias:</th>
			<td>{{ object.referencias }}</td>
		</tr>
		{% endif %}

		{% if object.descripcion %}
		<tr>
			<th>Descripcion:</th>
			<td>{{ object.descripcion }}</td>
		</tr>
		{% endif %}

		{% if object.observaciones %}
		<tr>
			<th>Observaciones:</th>
			<td>{{ object.observaciones }}</td>
		</tr>
		{% endif %}
		<tr>
			<th>Comisión pactada:</th>
			<td>{{ object.pct_pactada }} %</td>
		</tr>
		<tr>
			<th>Comisión a compartir:</th>
			<td>{{ object.pct_compartir }} %</td>
		</tr>

	</table>

	<ul>
		<li class="precio">{{ object.precio|intcomma }} {{ object.divisa.code }}</li>
		{% if object.habitaciones %}
		<li class="recamaras">{{ object.habitaciones }}</li>
		{% endif %}
		{% if object.banos %}
		<li class="banos">{{ object.banos }}</li>
		{% endif %}
		{% if object.estacionamientos %}
		<li class="estacionamientos">{{ object.estacionamientos }}</li>
		{% endif %}

	</ul>
	<table>
		{% services object object.get_general_fields 'properties/detail_services.html' exclude='precio, banos, estacionamientos, divisa, habitaciones'%}	
	</table>
	{% if object.get_extra_fields|length %}
	<p style="font-size:16px"><strong>Info Extras</strong></p>
	<table>
		{% services object object.get_extra_fields 'properties/detail_services.html' %}
	</table>
	{% endif %}

	{% if object.get_adicionales_fields|length %}
	<p style="font-size:16px"><strong>Adicionames Inmueble</strong></p>
	<table>
		{% services object object.get_adicionales_fields 'properties/detail_services.html' %}
	</table>
	{% endif %}


	{% if object.get_condominio_fields|length %}
	<p style="font-size:16px"><strong>Extras Condominio</strong></p>
	<table>
		{% services object object.get_condominio_fields 'properties/detail_services.html' %}
	</table>
	{% endif %}

	<hr>
	<h2>CONTACTAR AL VENDEDOR</h2>
	{% get_profile owner as owner_profile %}
	<p>{{ owner.get_full_name }}</p>
	<p>ID: {{ owner.profile.ref_id }}</p>

	{% if owner_profile.AMPI %}
	<p>Certicado: {{ owner_profile.AMPI }}<p>
	{% endif %}
	<p>Tel Celular: {{ owner_profile.phone1 }}</p>

	{% if owner_profile.phone2 %}
	<p>Tel Oficina/Casa: {{ owner_profile.phone2 }} </p>
	{% endif %}

	<a href="mailto:{{ owner.email }}">{{ owner.email }}</a></p>

</div><!-- /.redbox -->
{% endblock%}


{% block right_id %}galeria{% endblock %}


{% block profile_right %}

<a href="#none" title="Ver mapa" id="btn_mapa"><img src="{{ STATIC_URL }}images/ui/btn_mapa.png" alt="Mapa"></a>
<a href="#none" title="Agregar a Favoritos"
	id="btn_favoritos"
	class="{% if is_favourite %}favourite{% endif %}"></a>


<div class="slider">

	<!-- LARGE PICS -->
	<div id="slider" class="flexslider">
		<ul class="slides">
			{% for image in images %}
			{% thumbnail image.imagen image_size crop="center" upscale=1  as im %}
			<li><img src="{{ im.url }}" alt="" style="margin:{{ im|margin:image_size }}"></li>
			{% endthumbnail %}
			{% endfor %}
			<li><img src="http://maps.googleapis.com/maps/api/staticmap?center={{ object.get_google_maps_query }}&zoom=15&size={{ image_size }}&maptype=roadmap&sensor=true" alt="localización"></li>
		</ul>
	</div>

	<!-- THUMBNAILS -->
	<div id="carousel" class="flexslider">
		<ul class="slides">
			{% for image in images %}
			{% thumbnail image.imagen thmb_size crop="center" upscale=1  as im %}
			<li><img src="{{ im.url }}" alt=""></li>
			{% endthumbnail %}
			{% endfor %}
			<li><img id="map-image" src="http://maps.googleapis.com/maps/api/staticmap?center={{ object.get_google_maps_query }}&zoom=15&size={{ thmb_size }}&maptype=roadmap&sensor=true" alt="localización"></li>
		</ul>
	</div>
</div>

{% endblock %}

nube_inmobiliaria/templates/properties/detail_extra_services.html
<li class="{{ field_name }}">{{ verbose_name }}</li>

nube_inmobiliaria/templates/properties/detail_services.html
<tr class="service {{ field_name }}">
	<th class="verbose_name">{{ verbose_name|capfirst }}: </th>
	<td class="value">{{ value }}</td>
</tr>

nube_inmobiliaria/templates/properties/detail_services_popup.html
<li class="service">{{ verbose_name|capfirst }}: {{ value }}</li>

nube_inmobiliaria/templates/properties/edit.html
{% extends "core/profile/base.html" %}
{% load thumbnail %}

{% block extra_head %}
<script type="text/javascript" src="{{ STATIC_URL }}properties/js/properties.js"></script>
<script type="text/javascript"  src="{{ STATIC_URL }}js/vendor/jquery.ui.widget.js"></script>
<script type="text/javascript"  src="{{ STATIC_URL }}js/jquery.iframe-transport.js"></script>
<script type="text/javascript"  src="{{ STATIC_URL }}js/jquery.fileupload.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}properties/js/detail.js"></script>
{% endblock %}

{% block profile_id %}anadir{% endblock %}


{% block profile_class %}padding{% endblock %}


{% block profile_title %}Editar Propiedad{% endblock %}


{% block profile_content %}
<form action="{% url properties-delete object.id %}" method="post" id="main_form" autocomplete="off">
	{% csrf_token %}
	<input type="submit" value="Borrar" id="delete-button" class="continuar"/>
</form>

<ul>
	{% for field in form.visible_fields %}
		{% if field.errors %}
			<li class="error">
			{{ field.label }}: {{ field.errors|join:" ," }}
			</li>
		{% endif %}
	{% endfor%}
</ul>


<!-- ANADIR FOTOS -->
<div class="diagonals fix">

	<h2>A&ntilde;adir fotos</h2>
</div><!-- /.diagonals -->

<div class="someextrapadding">
    <p class="helptext">
    Recomendamos que las im&aacute;genes cargadas tengan una dimensión
    mínima de 700 x 690 pixeles
    </p>

	<p id="image-message" class="exito" style="display:none;"></p>
	<input id="id_imagen" type="file" name="imagen" data-url="{% url property-add-image object.id %}">

	<!--span>Prohibido subir fotos donde se muestre la fachada de la propiedad</span--!>

	<div class="clear"></div>

</div><!-- /.someextrapadding -->

<div id="fotos_box">
	{% for image in object.imagenes.all %}
	{% thumbnail image.imagen image.EDIT_SIZE crop="center" upscale=1 as im %}
	<span class="image-edit">
		<img src="{{ im.url }}"
		alt=""
		data-main-picture="{% url property-set-main-picture object.id image.id %}"
		id="image-id-{{ image.id }}"
		{% ifequal object.main_picture image %}class="main-picture"{% endifequal %}/>
		<a href="{% url property-delete-image object.id image.id %}" class="delete-image">borrar</a>
	</span>
	{% empty %}
	<div>nada {{ image.EDIT_SIZE }}</div>
	{% endthumbnail %}
	{% endfor %}
</div><!-- /#fotos_box -->

<div class="clear"></div>
<div class="diagonals fix">

	<h2>Editar Propiedad</h2>

</div><!-- /.diagonals -->
<form action="" method="post" id="main_form" autocomplete="off">
	{% csrf_token %}
	<div id="form_content" class="padding">
		{{ form.as_formated_div }}
	</div>
	<input type="submit" value="Guardar" id="edit-button" class="continuar"/>
</form>

{% endblock %}

nube_inmobiliaria/templates/properties/inmueble_form.html
<form action="" method="post"> 
{% csrf_token %}

{{ form.as_p }}

<input type="submit" value="Crear" /> 
</form> 